# Generated by Django 2.2 on 2019-08-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidateAnswer', models.CharField(max_length=255)),
                ('actualAnswer', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='TestIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_score', models.FloatField(default=0.0)),
                ('candidate_answers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.CandidateAnswers')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Candidate')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TestIdentifier')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=2082)),
                ('test_version', models.IntegerField(default=1)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TestIdentifier')),
            ],
        ),
        migrations.AddField(
            model_name='candidateanswers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='candidateanswers',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TestIdentifier'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_a', models.CharField(max_length=255)),
                ('answer_b', models.CharField(max_length=255)),
                ('answer_c', models.CharField(max_length=255)),
                ('answer_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TestIdentifier')),
            ],
        ),
    ]
