# Generated by Django 2.2 on 2019-08-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatelinkedtest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Candidate')),
                ('testidentifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TestIdentifier')),
            ],
        ),
    ]
