# Generated by Django 2.2 on 2019-09-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_candidatelinkedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='candidate_answers_id',
            field=models.CharField(max_length=2000),
        ),
    ]
